name: Trigger Dispatch on Push

on:
  push:
    branches:
      - main   

jobs:
  trigger-dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Send Dispatch Event
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT }}   
          repository: danielrosehill/Documetation-Root-Repo   
          event-type: update